// ── 전체 Site Code 목록 (78개) ────────────────────────────────
export const ALL_SITES = [
  { code:'CA_FR',     region:'NALA', name:'캐나다 (FR)',       flag:'🇨🇦' },
  { code:'CA',        region:'NALA', name:'캐나다',            flag:'🇨🇦' },
  { code:'MX',        region:'NALA', name:'멕시코',            flag:'🇲🇽' },
  { code:'BR',        region:'NALA', name:'브라질',            flag:'🇧🇷' },
  { code:'LATIN',     region:'NALA', name:'라틴아메리카',      flag:'🌎' },
  { code:'LATIN_EN',  region:'NALA', name:'라틴아메리카 (EN)', flag:'🌎' },
  { code:'CO',        region:'NALA', name:'콜롬비아',          flag:'🇨🇴' },
  { code:'AR',        region:'NALA', name:'아르헨티나',        flag:'🇦🇷' },
  { code:'PY',        region:'NALA', name:'파라과이',          flag:'🇵🇾' },
  { code:'UY',        region:'NALA', name:'우루과이',          flag:'🇺🇾' },
  { code:'CL',        region:'NALA', name:'칠레',              flag:'🇨🇱' },
  { code:'PE',        region:'NALA', name:'페루',              flag:'🇵🇪' },
  { code:'SG',        region:'APAC', name:'싱가포르',          flag:'🇸🇬' },
  { code:'AU',        region:'APAC', name:'호주',              flag:'🇦🇺' },
  { code:'NZ',        region:'APAC', name:'뉴질랜드',          flag:'🇳🇿' },
  { code:'ID',        region:'APAC', name:'인도네시아',        flag:'🇮🇩' },
  { code:'TH',        region:'APAC', name:'태국',              flag:'🇹🇭' },
  { code:'VN',        region:'APAC', name:'베트남',            flag:'🇻🇳' },
  { code:'MY',        region:'APAC', name:'말레이시아',        flag:'🇲🇾' },
  { code:'PH',        region:'APAC', name:'필리핀',            flag:'🇵🇭' },
  { code:'MM',        region:'APAC', name:'미얀마',            flag:'🇲🇲' },
  { code:'JP',        region:'APAC', name:'일본',              flag:'🇯🇵' },
  { code:'UK',        region:'EU',   name:'영국',              flag:'🇬🇧' },
  { code:'IE',        region:'EU',   name:'아일랜드',          flag:'🇮🇪' },
  { code:'DE',        region:'EU',   name:'독일',              flag:'🇩🇪' },
  { code:'AT',        region:'EU',   name:'오스트리아',        flag:'🇦🇹' },
  { code:'CH',        region:'EU',   name:'스위스',            flag:'🇨🇭' },
  { code:'CH_FR',     region:'EU',   name:'스위스 (FR)',       flag:'🇨🇭' },
  { code:'FR',        region:'EU',   name:'프랑스',            flag:'🇫🇷' },
  { code:'IT',        region:'EU',   name:'이탈리아',          flag:'🇮🇹' },
  { code:'GR',        region:'EU',   name:'그리스',            flag:'🇬🇷' },
  { code:'ES',        region:'EU',   name:'스페인',            flag:'🇪🇸' },
  { code:'PT',        region:'EU',   name:'포르투갈',          flag:'🇵🇹' },
  { code:'BE',        region:'EU',   name:'벨기에',            flag:'🇧🇪' },
  { code:'BE_FR',     region:'EU',   name:'벨기에 (FR)',       flag:'🇧🇪' },
  { code:'NL',        region:'EU',   name:'네덜란드',          flag:'🇳🇱' },
  { code:'SE',        region:'EU',   name:'스웨덴',            flag:'🇸🇪' },
  { code:'DK',        region:'EU',   name:'덴마크',            flag:'🇩🇰' },
  { code:'FI',        region:'EU',   name:'핀란드',            flag:'🇫🇮' },
  { code:'NO',        region:'EU',   name:'노르웨이',          flag:'🇳🇴' },
  { code:'PL',        region:'EU',   name:'폴란드',            flag:'🇵🇱' },
  { code:'RO',        region:'EU',   name:'루마니아',          flag:'🇷🇴' },
  { code:'BG',        region:'EU',   name:'불가리아',          flag:'🇧🇬' },
  { code:'HU',        region:'EU',   name:'헝가리',            flag:'🇭🇺' },
  { code:'CZ',        region:'EU',   name:'체코',              flag:'🇨🇿' },
  { code:'SK',        region:'EU',   name:'슬로바키아',        flag:'🇸🇰' },
  { code:'EE',        region:'EU',   name:'에스토니아',        flag:'🇪🇪' },
  { code:'LV',        region:'EU',   name:'라트비아',          flag:'🇱🇻' },
  { code:'LT',        region:'EU',   name:'리투아니아',        flag:'🇱🇹' },
  { code:'HR',        region:'EU',   name:'크로아티아',        flag:'🇭🇷' },
  { code:'RS',        region:'EU',   name:'세르비아',          flag:'🇷🇸' },
  { code:'SI',        region:'EU',   name:'슬로베니아',        flag:'🇸🇮' },
  { code:'AL',        region:'EU',   name:'알바니아',          flag:'🇦🇱' },
  { code:'MK',        region:'EU',   name:'북마케도니아',      flag:'🇲🇰' },
  { code:'BA',        region:'EU',   name:'보스니아',          flag:'🇧🇦' },
  { code:'UA',        region:'EU',   name:'우크라이나',        flag:'🇺🇦' },
  { code:'IN',        region:'SWA',  name:'인도',              flag:'🇮🇳' },
  { code:'BD',        region:'SWA',  name:'방글라데시',        flag:'🇧🇩' },
  { code:'AE',        region:'MENA', name:'UAE',               flag:'🇦🇪' },
  { code:'AE_AR',     region:'MENA', name:'UAE (AR)',          flag:'🇦🇪' },
  { code:'IL',        region:'MENA', name:'이스라엘',          flag:'🇮🇱' },
  { code:'PS',        region:'MENA', name:'팔레스타인',        flag:'🇵🇸' },
  { code:'SA',        region:'MENA', name:'사우디아라비아',    flag:'🇸🇦' },
  { code:'SA_EN',     region:'MENA', name:'사우디 (EN)',       flag:'🇸🇦' },
  { code:'TR',        region:'MENA', name:'터키',              flag:'🇹🇷' },
  { code:'IRAN',      region:'MENA', name:'이란',              flag:'🇮🇷' },
  { code:'LEVANT',    region:'MENA', name:'레반트',            flag:'🌍' },
  { code:'LEVANT_AR', region:'MENA', name:'레반트 (AR)',       flag:'🌍' },
  { code:'PK',        region:'MENA', name:'파키스탄',          flag:'🇵🇰' },
  { code:'EG',        region:'MENA', name:'이집트',            flag:'🇪🇬' },
  { code:'N_AFRICA',  region:'MENA', name:'북아프리카',        flag:'🌍' },
  { code:'AFRICA_EN', region:'MENA', name:'아프리카 (EN)',     flag:'🌍' },
  { code:'AFRICA_FR', region:'MENA', name:'아프리카 (FR)',     flag:'🌍' },
  { code:'AFRICA_PT', region:'MENA', name:'아프리카 (PT)',     flag:'🌍' },
  { code:'ZA',        region:'MENA', name:'남아프리카',        flag:'🇿🇦' },
  { code:'IQ_AR',     region:'MENA', name:'이라크 (AR)',       flag:'🇮🇶' },
  { code:'IQ_KU',     region:'MENA', name:'이라크 (KU)',       flag:'🇮🇶' },
  { code:'LB',        region:'MENA', name:'레바논',            flag:'🇱🇧' },
]

export const SITE_MAP = Object.fromEntries(ALL_SITES.map(s => [s.code, s]))

export const REGIONS = ['NALA', 'APAC', 'EU', 'SWA', 'MENA']

export const REGION_COLORS = {
  NALA: '#3b82f6', APAC: '#22c55e', EU: '#8b5cf6', SWA: '#f59e0b', MENA: '#ef4444',
}
export const REGION_BG = {
  NALA: '#eff6ff', APAC: '#f0fdf4', EU: '#f5f3ff', SWA: '#fffbeb', MENA: '#fef2f2',
}

export const STATUS_COLOR = {
  변경: { bg: '#dbeafe', fg: '#1e40af' },
  추가: { bg: '#dcfce7', fg: '#166534' },
  삭제: { bg: '#fee2e2', fg: '#991b1b' },
  동일: { bg: '#f3f4f6', fg: '#6b7280' },
}

// 카피 작업 진행 상태
export const COPY_STATUSES = [
  { value: '',               label: '— 미설정 —',      color: '#9ca3af', bg: '#f3f4f6' },
  { value: 'tp_translation', label: 'TP 번역',          color: '#7c3aed', bg: '#ede9fe' },
  { value: 'local_confirmed',label: 'Local Confirmed',  color: '#1d4ed8', bg: '#dbeafe' },
  { value: 'deck_merge',     label: 'Deck Merge',       color: '#b45309', bg: '#fef3c7' },
  { value: 'production',     label: 'Production',       color: '#166534', bg: '#dcfce7' },
]