name: Build Windows EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:    # 수동 실행도 가능하게

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install root dependencies
        run: npm install

      - name: Build client
        run: |
          cd client
          npm install
          npm run build

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Build EXE
        run: npm run build:win
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: dist/*.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - name: Build client
        run: |
          cd client
          npm install
          npm run build

      - name: Install server dependencies
        run: |
          cd server
          npm install

      - name: Build Mac APP
        run: npx electron-builder --mac
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Mac artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-app
          path: dist/*.dmg